# Generated by Django 5.2.3 on 2025-06-24 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("diaryAPI", "0001_initial"),
        ("diaryAPI", "0002_alter_diary_options_alter_diarytags_options_and_more"),
        ("diaryAPI", "0003_alter_diary_created"),
        ("diaryAPI", "0004_remove_diary_unique_entry_for_date_and_more"),
        ("diaryAPI", "0005_alter_diary_created"),
        ("diaryAPI", "0006_alter_diary_created"),
        ("diaryAPI", "0007_alter_diary_created"),
        ("diaryAPI", "0008_alter_diary_entry"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry", models.TextField(unique_for_date="created")),
                ("created", models.DateField(auto_now=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Diaries",
            },
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="DiaryTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diary_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="diaryAPI.diary"
                    ),
                ),
                (
                    "tag_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="diaryAPI.tags"
                    ),
                ),
            ],
            options={
                "unique_together": {("diary_id", "tag_id")},
                "verbose_name_plural": "Diary Tags",
            },
        ),
        migrations.AddConstraint(
            model_name="diary",
            constraint=models.UniqueConstraint(
                fields=("created", "entry"), name="unique_entry_for_date"
            ),
        ),
        migrations.AlterField(
            model_name="diary",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.RemoveConstraint(
            model_name="diary",
            name="unique_entry_for_date",
        ),
        migrations.AlterField(
            model_name="diary",
            name="created",
            field=models.DateField(auto_now_add=True, unique=True),
        ),
        migrations.AlterField(
            model_name="diary",
            name="entry",
            field=models.TextField(),
        ),
    ]
